import { WEATHER_WNI_LAYER_KEYS } from 'constants/layer/weather_wni'
import { WIND_LAYER_KEYS } from 'constants/layer/wind'

export const UNIT_FORMAT = {
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_UV]: 'm/s',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_UUU]: 'm/s',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WIND_UV]: 'knots',
  [WIND_LAYER_KEYS.WIND_TOOLTIP]: 'knots',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_TMP1000HPA]: '°C',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_SST]: '°C',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_PSWH_HEATMAP]: 'm',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_VISIBILITY]: 'm',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_PSWH_UV]: '°',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_INTPCP]: 'kg/m²'
}
