import { WEATHER_WNI_LAYER_KEYS } from 'constants/layer/weather_wni'
import { WIND_LAYER_KEYS } from 'constants/layer/wind'

export const UNIT_FORMAT = {
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WIND_TOOLTIP]: 'knots',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WAVE_TOOLTIP]: 'feet',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_OCEAN_CURRENT_TOOLTIP]: 'knots',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_PSWH_UV_TOOLTIP]: 'feet',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WAVE_UV]: 'feet',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WAVE_HEATMAP]: 'feet',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_OCEAN_CURRENT_UV]: 'm/s',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_WIND_UV]: 'knots',
  [WIND_LAYER_KEYS.WIND_TOOLTIP]: 'knots',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_AIR_TEMPERATURE]: '°C',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_SST]: '°C',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_PSWH_HEATMAP]: 'feet',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_VISIBILITY]: 'm',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_PSWH_UV]: '°',
  [WEATHER_WNI_LAYER_KEYS.WEATHER_WNI_INTPCP]: 'mm/hour'
}
