export const HOME_ROUTE = '/map'
export const LOGIN_ROUTE = '/login'
export const LOGIN_CONFIRM_ROUTE = '/login-confirm'
export const PASSWORD_SETUP_ROUTE = '/password-setup'
export const PASSWORD_RESET_ROUTE = '/password-reset'
export const SIGN_UP_ROUTE = '/sign-up'
